version: 3

tasks:
  install:client:
    cmds:
      - cd client &&
        npm install
  install:api:
    cmds:
      - cd api &&
        npm install &&
        docker compose up -d --build
  install:
    deps: [install:client, install:api]

  dev:api:
    cmds:
      - cd api &&
        docker compose up -d &&
        npm run start:dev -- --host
  dev:client:
    - cd client &&
      npm run dev

  dev:
    deps: [dev:api]
