export enum ProgramTemplateEnum {
  FULL_BODY,
  PUSH_PULL_LEGS,
  UPPER_LOWER,
  UPPER_LOWER_PUSH_PULL,
  PUSH_PULL_LEGS_CARDIO,
  PUSH_PULL_LEGS_PUSH_PULL_LEGS,
  PUSH_PULL_LEGS_UPPER_LOWER,
  CUSTOM
}